// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/cicbyte/weread-web/internal/dao/internal"
)

// articleImagesDao is the data access object for the table article_images.
// You can define custom methods on it to extend its functionality as needed.
type articleImagesDao struct {
	*internal.ArticleImagesDao
}

var (
	// ArticleImages is a globally accessible object for table article_images operations.
	ArticleImages = articleImagesDao{internal.NewArticleImagesDao()}
)

// Add your custom methods and functionality below.
