// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/cicbyte/weread-web/internal/dao/internal"
)

// authorsDao is the data access object for the table authors.
// You can define custom methods on it to extend its functionality as needed.
type authorsDao struct {
	*internal.AuthorsDao
}

var (
	// Authors is a globally accessible object for table authors operations.
	Authors = authorsDao{internal.NewAuthorsDao()}
)

// Add your custom methods and functionality below.
